<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CONTACT {0}' => 'СВЯЗАТЬСЯ С {0}',
    'Complaints / Abuse reports' => 'Жалобы',
    'E-mail' => '',
    'Fast communication' => '@@@@',
    'GET IN TOUCH' => 'ОБРАТНАЯ СВЯЗЬ',
    'Have questions?' => 'Есть вопросы?',
    'Help and feedback' => 'Помощь и обратная связь',
    'Message' => 'Сообщение',
    'Name' => 'Имя',
    'Notifications about spam, breaches of trademark, illegal or immoral activities of our clients:' => 'Уведомления о спаме, нарушениях торговых марок, противозаконной или аморальной деятельности наших клиентов:',
    'Notifications about spam, breaches of trademark, illegal or immoral activities of our clients: {0}' => '@@@@',
    'Other contact information' => '@@@@',
    'Our friendly Support Team is available to help you 24 hours a day' => 'Наша команда поддержки доступна 24 часа в сутки, чтобы помочь вам.',
    'Please note If you are already our customer and you require technical support, please open a support ticket in your <a href="{url}">control panel</a>.' => 'Внимание! Если Вы уже являетесь нашим клиентом и Вам требуется помощь тех.поддержки, пожалуйста, откройте тикет в <a href="{url}">панели управления</a>.',
    'Please note If you are already our customer and you require technical support, please open a support ticket in your {0}.' => '@@@@',
    'Please review the list of <a href="{url}">frequently asked questions</a> before contacting customer support.' => 'Пожалуйста, просмотрите список <a href="{url}">часто задаваемых вопросов</a>, перед тем как обратиться в службу поддержки.',
    'Sales' => 'Отдел продаж',
    'Subject' => 'Тема',
    'Submit' => 'Отправить',
    'Support information' => 'Отдел технической поддержки и администрирования',
    'Technical Support' => '@@@@',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Благодарим Вас за обращение к нам. Мы ответим вам как можно скорее.',
    'control panel' => '@@@@',
];
