<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Afilias Domain Anti-Abuse Policy' => 'Политика по борьбе со злоупотреблением Afilias',
    'Cancelation & Refunds' => 'Правила отказа от услуг',
    'Cancelation policy' => 'Правила предоставления услуг',
    'Capacity building insurmountable challenges, Andrew Carnegie rural development' => '',
    'Contact Us' => 'обратитесь к нам',
    'Domain removal and auto renewal Policy' => 'Правила автопродления и удаления домена',
    'Privacy Policy' => 'Политика конфиденциальности',
    'Registrant rights and responsibilities' => 'Права и обязаности регистранта',
    'Rules' => 'Правила',
    'Terms of use' => 'Правила использования',
    'Domain Name Registration Agreement' => 'Соглашение о регистрации доменных имен',
];
