<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Domain names search and registration' => 'Поиск и регистрация доменных имён',
    'Domain pricing' => 'Цены на домены',
    'Domain search' => 'Поиск доменов',
    'PAYMENT METHODS' => 'СПОСОБЫ ОПЛАТЫ',
    'Registration' => 'Регистрация',
    'Renewal' => 'Продление',
    'START BY REGISTERING YOUR DOMAIN NAME' => 'НАЧНИТЕ С РЕГИСТРАЦИИ ВАШЕГО ДОМЕННОГО ИМЕНИ',
    'Today our company, offers the most competitive and fair prices for domain registration services. Due to the large number of domains that are in our care, we get a significant discount from our registrar. This creates a very positive impact on the price of domain names offered to you!' => 'Мы предлагаем вам высочайший уровень надежности по самым разумным и доступным ценам в Сети Интернет. Наша цена регистрации включает квалифицированную поддержку, которая профессионально и в максимально сжатые сроки решающая все проблемы клиентов, связанные с регистрацией и использованием доменов, и неукоснительное соблюдение всех прав пользователя в управлении доменом на предоплаченный им период. Оплачивая регистрацию или продление домена у нас вы оплачиваете год спокойствия и уверенности в надежности сервиса, которому доверяете самое главное – ваш интернет-ресурс.',
    'Transfer' => 'Трансфер',
    'We accept the following automatic payment methods' => 'Мы принимаем к оплате в автоматическом режиме следующие платежные системы',
    'Zone' => 'Доменные зоны',
    'as well as PayPal payments from your Visa and MasterCard' => 'а также платежные карты Visa и MasterCard, процессинг которых осуществляется через PayPal.',
];
