<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'CONTACT {0}' => '',
    'Complaints / Abuse reports' => '',
    'Fast communication' => '',
    'GET IN TOUCH' => '',
    'Have questions?' => '',
    'Help and feedback' => '',
    'Notifications about spam, breaches of trademark, illegal or immoral activities of our clients: {0}' => '',
    'Other contact information' => '',
    'Our friendly Support Team is available to help you 24 hours a day' => '',
    'Please note If you are already our customer and you require technical support, please open a support ticket in your {0}.' => '',
    'Sales' => '',
    'Technical Support' => '',
    'Thank you for contacting us. We will respond to you as soon as possible.' => '',
    'control panel' => '',
];
