<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Domain</strong> - an alphanumeric name that uniquely identifies a particular website.' => '<strong>Домен</strong> – это алфавитно-цифровое имя, которое является уникальным идентификатором конкретного web-узла.',
    'BASIC PACKAGE' => 'БАЗОВЫЙ ПАКЕТ',
    'CNAME' => '',
    'Comparing the basic and premium DNS management pack' => 'Сравнения базового и премиум-пакета управления',
    'DNS' => '',
    'DNS management packs' => 'Пакеты управления DNS',
    'Domain auto renewal option' => '',
    'Domain parking' => '',
    'Editing of SOA record' => 'Редактировать SOA записи.',
    'Editing of TTL values' => 'Редактировать TTL записи.',
    'Free DNS-servers located in different data - centers: the Netherlands (NL) and the U.S. (US).' => 'Бесплатные DNS-сервера, расположенные в разных дата - центрах: Нидерланды (NL) и Америка (US).',
    'MX' => '',
    'Management packages' => 'Пакеты управления',
    'NS' => '',
    'PREMIUM PACKAGE' => 'ПРЕМИУМ-ПАКЕТ',
    'Please note that if you have previously activated the "Premium Package", but do not want to pay for this feature, all previously made settings for domains will remain and will continue to function normally, but you will not be able to change or delete records.' => 'Обращаем ваше внимание на то, что если у вас ранее был активирован «Premium DNS», но вы не желаете использовать его на платной основе, то все ранее внесенные настройки для доменов остануться и продолжат функционировать в штатном режиме, однако вы будете лишены возможности вносить изменения и удалять записи.',
    'Preinstalled settings for Google Apps' => 'Предустановленные настройки для Google Apps.',
    'SOA' => '',
    'TXT' => '',
    'Terms of Use for "Premium Package".' => 'Условия использования "Премиум-пакета управления DNS".',
    'The total number of A and CName records' => 'Общее количество записей A и CNAME.',
    'Types of records available for editing: A, AAAA, MX, CNAME, TXT, NS.' => 'Типы записей, доступных для редактирования: A, AAAA, MX, CNAME, TXT, NS.',
    'URL and E-mail forwarding' => 'Переадресации электронной почты и URL.',
    'Working with subdomains' => 'Работа с под-доменами',
    '{aaaa} - a similar record that uses the address of the new Pv6 standard.' => '{aaaa} - аналогична А-записи, но использует адрес в новом стандарте IPv6.',
    '{a} - a record that binds the hostname to an IP-address where the resource is located.' => '{a} - запись, связывает имя хоста с IP-адресом, по которому находится ресурс.',
    '{cname} - the canonical name or "alias" that is used to redirect requests from one domain name to another.' => '{cname} - является канонической записью имени или «псевдонимом» по простому и используется для перенаправления запросов с одного доменного имени, на другое.',
    '{dns} - a network service that provides information about domains. Each computer connected to the Internet has a unique IP-address, made up of many numbers that are difficult to memorize. A Domain Name System (DNS) allows you to replace the numbers with a description of your choice, making it easier to find the correct one.' => '{dns} - это сетевая служба, служащая для получения информации о доменах. Так как каждый компьютер в сети Интернет имеет свой уникальный IP-адрес, выполненный в сложном для запоминания виде, система доменных имен (DNS) позволяет заменять эти номера, буквами упрощая поиск нужного web-ресурса.',
    '{mx} - a record that points to the IP-address of the mail server of a domain.' => '{mx} - запись, указывает на IP-адрес почтового сервера данного домена.',
    '{ns} - indicates the IP-address of the DNS-server for this domain.' => '{ns} – указывает на IP-адрес, где находится DNS-сервер для данного домена.',
    '{soa} - a parameter that specifies which server stores the reference entry for your domain, stores the contact information and the caching information about the DNS-server interaction.' => '{soa} – параметр, указывающий, на каком сервере хранится эталонная запись о вашем домене, хранит контактную информацию ответственного лица, время кэширования и информации о взаимодействии DNS-серверов.',
    '{txt} - indicates the IP-address that is used by the DNS-server of a domain.' => '{txt} – как правило, содержит произвольную текстовую информацию о данном домене.',
    'А' => '',
    'АААА' => '',
];
