<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'О нас',
    'Complaints / Abuse reports' => 'Жалобы',
    'Contact information' => 'Контактная информация',
    'Fast communication' => 'Быстрая связь',
    'Notifications about spam, breaches of trademark, illegal or immoral activities of our clients:' => 'Уведомления о спаме, нарушениях торговых марок, противозаконной или аморальной деятельности наших клиентов:',
    'On this list our services does not end — we are constantly working on new projects, as well as improving existing services.' => 'На этом перечень наших возможностей не заканчивается — мы постоянно работаем над новыми проектами, а также совершенствуем и улучшаем имеющиеся сервисы.',
    'Originally {org_name} started as a project of {parent_org_name} company. Today it is a completely independent resource, that provides domain registration and hosting (VPS) for over 7 years. {org_name} team — is a staff of professionals with great experience. We strive to provide quality services and optimal solutions for all online projects.' => 'Изначально {org_name} стартовал как проект компании {parent_org_name}. Сегодня — это полностью самостоятельный ресурс, который предоставляет услуги по регистрации доменов и хостингу (VDS) уже более 7-ми лет. Команда {org_name} — это штат профессионалов с большим опытом. Мы стремимся предоставлять качественные услуги и оптимальные решения для любых интернет-проектов.',
    'Sales' => 'Отдел продаж',
    'Technical Support and Administration' => 'Отдел технической поддержки и администрирования',
    'VPS-clock monitoring;' => 'Круглосуточный мониторинг VDS;',
    'We provide reliable web hosting along with powerful networking and system solutions that enable our customers to realize their business goals at any level of complexity. Through our professional expertise and latest technology available on the market, {org_name} provides the most efficient, reliable and easily managed solutions to meet our clients\' needs.' => '{org_name} предоставляет надежные хостинговые, сетевые и системные решения, позволяющие нашим клиентам реализовать их деловые цели любого уровня сложности. Работая с лучшими технологиями на рынке, мы предоставляем гибкость и уровень контроля, которые гарантируют Вам как клиенту наиболее эффективное, надежное и легко управляемое техническое решение для Ваших задач.',
    'We understand that reliability and speed are a top priority for internet projects. And we know how to do it. We had a great experience, and we continue to grow, listening to all the customers needs and market trends. With us you can be certain of the best solution!' => 'Мы понимаем, как важны для интернет-проекта надежность и скорость работы. И знаем, как это сделать. За нашими плечами — большой опыт работы, и мы продолжаем развиваться, прислушиваясь ко всем пожеланиям клиентов и тенденциям рынка. С нами вы можете быть уверенны в том, что выбрали самое оптимальное решение!',
    'What is {org_name}?' => 'Что такое {org_name}?',
    'Why {org_name}?' => 'Почему {org_name}?',
    'convenient control panel of our own design;' => 'Удобная панель управления собственной разработки;',
    'professional technical support 24/7;' => 'Профессиональная техподдержка 24/7;',
    '{org_name} customers always receive high quality technical support, an individual approach to solving problems, convenient payment system and regular discounts.' => 'Клиенты {org_name} всегда получают качественную техподдержку, индивидуальный подход в решении задач, удобную систему оплаты и постоянные скидки.',
    '{org_name} mobile app for Android;' => 'Мобильное приложение {org_name} для Android;',
    '{org_name} services' => 'Услуги {org_name}',
    '{org_name} services are: domain search, registration and transfer, as well as hosting for your projects (VPS). In addition, for users are available:' => 'Услуги {org_name} – это поиск, регистрация и трансфер доменов, а также хостинг для ваших проектов (VDS). Кроме того, пользователям доступны:

',
];
