<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Creating subsidiary NS-servers' => '',
    'DNS Server setup' => '',
    'Errors and problems' => '',
    'FAQ' => '',
    'Find answers to the common questions asked about our services' => '',
    'Hosting' => '',
    'Installing third-party NS-servers' => '',
    'NS Server installation' => '',
    'Other' => '',
    'Transfer' => '',
    'Transferring domain to other registrar' => '',
    'Transferring domain to other user' => '',
    'Transferring domain to {host}' => '',
    'Verification' => '',
    '{host} NS-server installation' => '',
];
