<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Domain</strong> - an alphanumeric name that uniquely identifies a particular website.' => '<strong>Домен</strong> – это алфавитно-цифровое имя, которое является уникальным идентификатором конкретного web-узла.',
    'BASIC PACKAGE' => 'БАЗОВЫЙ ПАКЕТ',
    'CNAME' => '',
    'Comparing the basic and premium DNS management pack' => 'Сравнения базового и премиум-пакета управления',
    'DNS' => '',
    'DNS management packs' => '',
    'Domain auto renewal option' => '',
    'Domain parking' => '',
    'Editing of SOA record' => '',
    'Editing of TTL values' => '',
    'Free DNS-servers located in different data - centers: the Netherlands (NL) and the U.S. (US).' => '',
    'MX' => '',
    'Management packages' => '',
    'NS' => '',
    'PREMIUM PACKAGE' => '',
    'Please note that if you have previously activated the "Premium Package", but do not want to pay for this feature, all previously made settings for domains will remain and will continue to function normally, but you will not be able to change or delete records.' => 'Обращаем ваше внимание на то, что если у вас ранее был активирован «Premium DNS», но вы не желаете использовать его на платной основе, то все ранее внесенные настройки для доменов остануться и продолжат функционировать в штатном режиме, однако вы будете лишены возможности вносить изменения и удалять записи.',
    'Preinstalled settings for Google Apps' => '',
    'SOA' => '',
    'TXT' => '',
    'Terms of Use for "Premium Package".' => 'Условия использования "Премиум-пакета управления DNS".',
    'The total number of A and CName records' => '',
    'Types of records available for editing: A, AAAA, MX, CNAME, TXT, NS.' => '',
    'URL and E-mail forwarding' => '',
    'Working with subdomains' => '',
    '{aaaa} - a similar record that uses the address of the new Pv6 standard.' => '',
    '{a} - a record that binds the hostname to an IP-address where the resource is located.' => '',
    '{cname} - the canonical name or "alias" that is used to redirect requests from one domain name to another.' => '',
    '{dns} - a network service that provides information about domains. Each computer connected to the Internet has a unique IP-address, made up of many numbers that are difficult to memorize. A Domain Name System (DNS) allows you to replace the numbers with a description of your choice, making it easier to find the correct one.' => '',
    '{mx} - a record that points to the IP-address of the mail server of a domain.' => '',
    '{ns} - indicates the IP-address of the DNS-server for this domain.' => '',
    '{soa} - a parameter that specifies which server stores the reference entry for your domain, stores the contact information and the caching information about the DNS-server interaction.' => '',
    '{txt} - indicates the IP-address that is used by the DNS-server of a domain.' => '',
    'А' => '',
    'АААА' => '',
];
