<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Hosting by {name} is an optimal and reliable solution for any project at affordable price.' => 'Хостинг {name} является оптимальным и надежным решением для любого проекта по доступной цене.',
    'The main advantage of a VDS based on XEN with SSD is speed. It is more than 250 times faster than a conventional HDD. Due to Xen virtualization type, all resources are assigned to user and the operation of your VDS does not depend on the main server\'s load.' => 'Основное преимущество VDS на базе Xen с применением SSD — скорость работы, которая выше более чем в 250 раз по сравнению с обычными HDD. Благодаря типу виртуализации Xen, все ресурсы гарантированно закреплены за пользователем, и работа вашего VDS не зависит от общей нагрузки на сервер.',
    'VDS Pricing' => 'Ценаы на VDS',
    'VPS based on OpenVZ — is an inexpensive and reliable solution for small projects that do not require many resources (HTML web-sites, landing pages, small blogs, personal websites, business cards, etc.). An additional advantage of our VPS based on OpenVZ is utilization of SSD cache system that improves performance of the disk subsystem during frequently accessed data readings.' => 'VDS на базе OpenVZ — это недорогой и надежный вариант для размещения проектов, не требующих большого количества ресурсов (HTML-сайты, лендинги, небольшие блоги, сайты-визитки и пр.). Дополнительным преимуществом наших VDS на базе OpenVZ является использование системы кеширования с SSD, что увеличивает производительность дисковой подсистемы на чтение часто запрашиваемых данных.',
    'Virtual dedicated server based on Xen is a perfect solution for most medium and large projects because of its performance that is highly competitive with the performance of a dedicated server.' => 'Виртуальный выделенный сервер на базе Xen — идеальное решение для большинства проектов средней и большой сложности, так как порой не уступает по производительности выделенному серверу.',
];
